# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 15:12
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20161031_1457'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'base_manager_name': '_plain_manager'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'base_manager_name': '_plain_manager'},
        ),
        migrations.AlterModelOptions(
            name='content',
            options={'base_manager_name': '_plain_manager'},
        ),
        migrations.AlterModelManagers(
            name='article',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_plain_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='category',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_plain_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='content',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_plain_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
