# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 10:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20161031_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
