# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 12:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20161027_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='permalink',
            field=models.CharField(default='1', max_length=200),
            preserve_default=False,
        ),
    ]
