# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-02 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_media_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='thumbnail',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='/Users/astagi/lotrek/camomilla4/media/thumbnails'),
        ),
    ]
