# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 16:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20161027_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='permalink',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
