# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-03 09:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20161103_0826'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='is_image',
            field=models.BooleanField(default=False),
        ),
    ]
