# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 18:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0007_auto_20161027_1745'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('permalink', models.CharField(max_length=200, unique=True)),
                ('content', models.TextField()),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('PUB', 'Published'), ('DRF', 'Draft'), ('TRS', 'Trash')], default='DRF', max_length=3)),
                ('date', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
