# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 09:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='subtitle',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
