# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 09:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_content_subtitle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='description',
        ),
    ]
