# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 10:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_content_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('dimension', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
    ]
