# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 12:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
