# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-30 09:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20161028_1209'),
    ]

    operations = [
        migrations.CreateModel(
            name='SitemapUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200, unique=True)),
                ('title', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('canonical', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('robots', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('og_image', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('og_description', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('og_title', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('og_type', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('og_url', models.CharField(blank=True, default='', max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='canonical',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='og_description',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='og_image',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='og_title',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='og_type',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='og_url',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='robots',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
