# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-29 12:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camomilla', '0002_auto_20161228_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='identifier',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name='content',
            unique_together=set([('page', 'identifier')]),
        ),
    ]
