# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-25 14:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camomilla', '0008_auto_20170323_2341'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='identifier',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='articletranslation',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
