# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-09-27 13:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camomilla', '0020_auto_20171128_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorytranslation',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='categorytranslation',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
    ]
