# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-11-14 22:48
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('camomilla', '0025_article_trash'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='article',
            managers=[
                ('trashmanager', django.db.models.manager.Manager()),
                ('_plain_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
