# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-02 18:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PUB', 'Published'), ('DRF', 'Draft'), ('TRS', 'Trash')], default='DRF', max_length=3)),
                ('date', models.DateTimeField(auto_now=True)),
                ('og_image', models.URLField(blank=True, default='', null=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'permissions': (('read_article', 'Can read article'),),
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_plain_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ArticleTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('permalink', models.CharField(max_length=200)),
                ('og_description', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('og_title', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('og_type', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('og_url', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('canonical', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('language_code', models.CharField(db_index=True, max_length=15)),
                ('master', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='camomilla.Article')),
            ],
            options={
                'abstract': False,
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'db_table': 'camomilla_article_translation',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'categories',
                'abstract': False,
                'permissions': (('read_category', 'Can read category'),),
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_plain_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='CategoryTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('language_code', models.CharField(db_index=True, max_length=15)),
                ('master', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='camomilla.Category')),
            ],
            options={
                'abstract': False,
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'db_table': 'camomilla_category_translation',
            },
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PUB', 'Published'), ('DRF', 'Draft'), ('TRS', 'Trash')], default='DRF', max_length=3)),
                ('date', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'permissions': (('read_content', 'Can read content'),),
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_plain_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ContentTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('content', models.TextField()),
                ('permalink', models.CharField(max_length=200)),
                ('language_code', models.CharField(db_index=True, max_length=15)),
                ('master', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='camomilla.Content')),
            ],
            options={
                'abstract': False,
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'db_table': 'camomilla_content_translation',
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('thumbnail', models.ImageField(blank=True, max_length=500, null=True, upload_to='thumbnails')),
                ('created', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('size', models.IntegerField(blank=True, default=0, null=True)),
                ('is_image', models.BooleanField(default=False)),
            ],
            options={
                'permissions': (('read_media', 'Can read media'),),
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_plain_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='MediaTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alt_text', models.CharField(blank=True, max_length=200, null=True)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('language_code', models.CharField(db_index=True, max_length=15)),
                ('master', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='camomilla.Media')),
            ],
            options={
                'abstract': False,
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'db_table': 'camomilla_media_translation',
            },
        ),
        migrations.CreateModel(
            name='SitemapUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(max_length=200, unique=True)),
                ('og_image', models.URLField(blank=True, default='', null=True)),
            ],
            options={
                'abstract': False,
                'permissions': (('read_sitemapurl', 'Can read sitemap url'),),
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_plain_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='SitemapUrlTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('permalink', models.CharField(max_length=200)),
                ('og_description', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('og_title', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('og_type', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('og_url', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('canonical', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('language_code', models.CharField(db_index=True, max_length=15)),
                ('master', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='camomilla.SitemapUrl')),
            ],
            options={
                'abstract': False,
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'db_table': 'camomilla_sitemapurl_translation',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
                'permissions': (('read_tag', 'Can read tag'),),
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_plain_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='TagTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('language_code', models.CharField(db_index=True, max_length=15)),
                ('master', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='camomilla.Tag')),
            ],
            options={
                'abstract': False,
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'db_table': 'camomilla_tag_translation',
            },
        ),
        migrations.AddField(
            model_name='content',
            name='page',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='camomilla.SitemapUrl'),
        ),
        migrations.AddField(
            model_name='article',
            name='categories',
            field=models.ManyToManyField(blank=True, to='camomilla.Category'),
        ),
        migrations.AddField(
            model_name='article',
            name='highlight_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='camomilla.Media'),
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, to='camomilla.Tag'),
        ),
        migrations.AlterUniqueTogether(
            name='tagtranslation',
            unique_together=set([('language_code', 'master')]),
        ),
        migrations.AlterUniqueTogether(
            name='sitemapurltranslation',
            unique_together=set([('language_code', 'master')]),
        ),
        migrations.AlterUniqueTogether(
            name='mediatranslation',
            unique_together=set([('language_code', 'master')]),
        ),
        migrations.AlterUniqueTogether(
            name='contenttranslation',
            unique_together=set([('permalink', 'language_code'), ('language_code', 'master')]),
        ),
        migrations.AlterUniqueTogether(
            name='categorytranslation',
            unique_together=set([('language_code', 'master')]),
        ),
        migrations.AlterUniqueTogether(
            name='articletranslation',
            unique_together=set([('permalink', 'language_code'), ('language_code', 'master')]),
        ),
    ]
