# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-30 01:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('camomilla', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='articletranslation',
            unique_together=set([('permalink', 'language_code'), ('language_code', 'master')]),
        ),
        migrations.AlterUniqueTogether(
            name='contenttranslation',
            unique_together=set([('permalink', 'language_code'), ('language_code', 'master')]),
        ),
    ]
