# Generated by Django 2.2.3 on 2019-09-11 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('camomilla', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='page',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contents', to='camomilla.Page'),
        ),
    ]
