# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-15 23:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('camomilla', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alt_text', models.CharField(blank=True, max_length=200, null=True)),
                ('language_code', models.CharField(db_index=True, max_length=15)),
                ('master', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='camomilla.Media')),
            ],
            options={
                'db_table': 'camomilla_media_translation',
                'db_tablespace': '',
                'abstract': False,
                'managed': True,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SitemapUrlTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('permalink', models.CharField(max_length=200)),
                ('og_description', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('og_title', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('og_type', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('og_url', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('canonical', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('language_code', models.CharField(db_index=True, max_length=15)),
            ],
            options={
                'db_table': 'camomilla_sitemapurl_translation',
                'db_tablespace': '',
                'abstract': False,
                'managed': True,
                'default_permissions': (),
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={},
        ),
        migrations.AlterModelManagers(
            name='sitemapurl',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_plain_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='article',
            name='canonical',
        ),
        migrations.RemoveField(
            model_name='article',
            name='og_description',
        ),
        migrations.RemoveField(
            model_name='article',
            name='og_title',
        ),
        migrations.RemoveField(
            model_name='article',
            name='og_type',
        ),
        migrations.RemoveField(
            model_name='article',
            name='og_url',
        ),
        migrations.RemoveField(
            model_name='article',
            name='robots',
        ),
        migrations.RemoveField(
            model_name='sitemapurl',
            name='canonical',
        ),
        migrations.RemoveField(
            model_name='sitemapurl',
            name='description',
        ),
        migrations.RemoveField(
            model_name='sitemapurl',
            name='og_description',
        ),
        migrations.RemoveField(
            model_name='sitemapurl',
            name='og_image',
        ),
        migrations.RemoveField(
            model_name='sitemapurl',
            name='og_title',
        ),
        migrations.RemoveField(
            model_name='sitemapurl',
            name='og_type',
        ),
        migrations.RemoveField(
            model_name='sitemapurl',
            name='og_url',
        ),
        migrations.RemoveField(
            model_name='sitemapurl',
            name='robots',
        ),
        migrations.RemoveField(
            model_name='sitemapurl',
            name='title',
        ),
        migrations.AddField(
            model_name='articletranslation',
            name='canonical',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='articletranslation',
            name='og_description',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='articletranslation',
            name='og_title',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='articletranslation',
            name='og_type',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='articletranslation',
            name='og_url',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='categories',
            field=models.ManyToManyField(blank=True, to='camomilla.Category'),
        ),
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, to='camomilla.Tag'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='level',
            field=models.CharField(choices=[('1', 'Guest'), ('2', 'Editor'), ('3', 'Admin')], default='1', max_length=3),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sitemapurltranslation',
            name='master',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='camomilla.SitemapUrl'),
        ),
        migrations.AddField(
            model_name='article',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='camomilla.Page'),
        ),
        migrations.AddField(
            model_name='sitemapurl',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='camomilla.Page'),
        ),
        migrations.AlterUniqueTogether(
            name='sitemapurltranslation',
            unique_together=set([('language_code', 'master')]),
        ),
        migrations.AlterUniqueTogether(
            name='mediatranslation',
            unique_together=set([('language_code', 'master')]),
        ),
    ]
