# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-15 23:31
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('camomilla', '0002_auto_20161115_2328'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='media',
            options={'base_manager_name': '_plain_manager'},
        ),
        migrations.AlterModelManagers(
            name='media',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_plain_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
