# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-19 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camomilla', '0003_auto_20161229_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagtranslation',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AlterField(
            model_name='articletranslation',
            name='permalink',
            field=models.SlugField(max_length=200),
        ),
    ]
