# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-21 19:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camomilla', '0003_auto_20161115_2331'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediatranslation',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
