# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-21 15:14
from __future__ import unicode_literals

from django.db import migrations, models
from django.conf import settings
from django.db import connection
import os


def select_image_path(self):
    with connection.cursor() as cursor:
        cursor.execute("SELECT og_image FROM camomilla_article WHERE id = %s", [self.pk])
        row = cursor.fetchone()
    return row


media_list = {}


def save_images(apps, schema_editor):

    Article = apps.get_model('camomilla', 'Article')

    for instance in Article.objects.all().iterator():
        db_row = select_image_path(instance)
        if len(db_row):
            media_list[str(instance.pk)] = db_row[0]


def reverse_save_images(apps, schema_editor):
    pass


def migrate_images(apps, schema_editor):

    Article = apps.get_model('camomilla', 'Article')
    Media = apps.get_model('camomilla', 'Media')

    for pk, image_name in media_list.items():
        image_path = os.path.join(settings.MEDIA_ROOT, image_name)
        if not os.path.isfile(image_path):
            continue
        m = Media.objects.create(name=image_name)
        with open(image_path, 'rb') as f:
            m.file.save(image_name, f)
            s = Article.objects.get(pk=pk)
            s.og_image = m
            s.save()


def reverse_migrate_images(apps, schema_editor):
    pass




class Migration(migrations.Migration):

    dependencies = [
        ('camomilla', '0004_auto_20170119_1629'),
    ]

    operations = [
        migrations.RunPython(save_images, reverse_save_images),
        migrations.AlterField(
            model_name='article',
            name='og_image',
            field=models.ImageField(blank=True, default='', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='sitemapurl',
            name='og_image',
            field=models.ImageField(blank=True, default='', null=True, upload_to=''),
        ),
        migrations.RunPython(migrate_images, reverse_migrate_images),
    ]
