# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-04 20:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camomilla', '0005_auto_20170221_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagtranslation',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name='tagtranslation',
            unique_together=set([('language_code', 'master'), ('title', 'language_code')]),
        ),
    ]
