# Generated by Django 2.2.25 on 2022-01-03 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("camomilla", "0005_media_image_props"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="media",
            name="is_image",
        ),
        migrations.AddField(
            model_name="media",
            name="mime_type",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
