# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-21 23:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('camomilla', '0005_auto_20161121_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitemapurl',
            name='og_image',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='page',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='camomilla.Page'),
        ),
        migrations.AlterField(
            model_name='sitemapurl',
            name='page',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='camomilla.Page'),
        ),
    ]
