# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-23 23:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camomilla', '0007_auto_20161122_1059'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AlterField(
            model_name='article',
            name='og_image',
            field=models.URLField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='sitemapurl',
            name='og_image',
            field=models.URLField(blank=True, default='', null=True),
        ),
    ]
