# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-23 23:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camomilla', '0007_auto_20170323_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitemapurltranslation',
            name='permalink',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
