# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-25 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camomilla', '0010_auto_20170325_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='identifier',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
