# Generated by Django 4.0.4 on 2023-01-12 11:05

from django.db import migrations, models
from ..contrib.modeltranslation.hvad_migration import KeepTranslationsMixin


class Migration(KeepTranslationsMixin, migrations.Migration):

    dependencies = [
        ('camomilla', '0011_auto_20220902_1000'),
    ]

    keep_translations = {
        "camomilla.Article": (
            "title",
            "description",
            "permalink",
            "og_description",
            "og_title",
            "og_type",
            "og_url",
            "canonical",
            "content",
        ),
        "camomilla.Tag": ("title",),
        "camomilla.Category": ("title", "description", "slug"),
        "camomilla.Content": ("title", "subtitle", "permalink", "content"),
        "camomilla.MediaFolder": ("title", "description"),
        "camomilla.Media": ("title", "description", "alt_text"),
        "camomilla.Page": (
            "title",
            "description",
            "permalink",
            "og_description",
            "og_title",
            "og_type",
            "og_url",
            "canonical",
        ),
    }
    
    operations = [
        migrations.AlterUniqueTogether(
            name='categorytranslation',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='categorytranslation',
            name='master',
        ),
        migrations.AlterUniqueTogether(
            name='contenttranslation',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='contenttranslation',
            name='master',
        ),
        migrations.AlterUniqueTogether(
            name='mediafoldertranslation',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='mediafoldertranslation',
            name='master',
        ),
        migrations.AlterUniqueTogether(
            name='mediatranslation',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='mediatranslation',
            name='master',
        ),
        migrations.AlterUniqueTogether(
            name='pagetranslation',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='pagetranslation',
            name='master',
        ),
        migrations.AlterUniqueTogether(
            name='tagtranslation',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='tagtranslation',
            name='master',
        ),
        migrations.AlterModelManagers(
            name='article',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='category',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='content',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='media',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='mediafolder',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='page',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='tag',
            managers=[
            ],
        ),
        migrations.AlterUniqueTogether(
            name='content',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='article',
            name='_hvad_query',
        ),
        # migrations.RemoveField(
        #     model_name='category',
        #     name='_hvad_query',
        # ),
        migrations.RemoveField(
            model_name='media',
            name='_hvad_query',
        ),
        migrations.RemoveField(
            model_name='mediafolder',
            name='_hvad_query',
        ),
        migrations.RemoveField(
            model_name='page',
            name='_hvad_query',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='_hvad_query',
        ),
        migrations.AddField(
            model_name='article',
            name='canonical',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='canonical_en',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='canonical_it',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='article',
            name='content_en',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='content_it',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='description_en',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='description_it',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='og_description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='og_description_en',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='og_description_it',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='og_title',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='og_title_en',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='og_title_it',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='og_type',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='og_type_en',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='og_type_it',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='og_url',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='og_url_en',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='og_url_it',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='permalink',
            field=models.SlugField(max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='article',
            name='permalink_en',
            field=models.SlugField(max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='article',
            name='permalink_it',
            field=models.SlugField(max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='title_it',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='description_en',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='description_it',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='slug_en',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='slug_it',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='title_it',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='content',
            name='content_en',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='content_it',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='permalink',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='permalink_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='permalink_it',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='subtitle',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='subtitle_en',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='subtitle_it',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='title_it',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='media',
            name='alt_text',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='media',
            name='alt_text_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='media',
            name='alt_text_it',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='media',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='media',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='media',
            name='description_it',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='media',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='media',
            name='title_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='media',
            name='title_it',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='mediafolder',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='mediafolder',
            name='description_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='mediafolder',
            name='description_it',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='mediafolder',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='mediafolder',
            name='title_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='mediafolder',
            name='title_it',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='canonical',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='canonical_en',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='canonical_it',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='description_en',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='description_it',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='og_description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='og_description_en',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='og_description_it',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='og_title',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='og_title_en',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='og_title_it',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='og_type',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='og_type_en',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='og_type_it',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='og_url',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='og_url_en',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='og_url_it',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='permalink',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='page',
            name='permalink_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='permalink_it',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='title_it',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='title',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='title_en',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='title_it',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='identifier',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='identifier',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.DeleteModel(
            name='ArticleTranslation',
        ),
        migrations.DeleteModel(
            name='CategoryTranslation',
        ),
        migrations.DeleteModel(
            name='MediaFolderTranslation',
        ),
        migrations.DeleteModel(
            name='MediaTranslation',
        ),
        migrations.DeleteModel(
            name='PageTranslation',
        ),
        migrations.DeleteModel(
            name='TagTranslation',
        ),
        migrations.RemoveField(
            model_name='content',
            name='_hvad_query',
        ),
        migrations.DeleteModel(
            name='ContentTranslation',
        ),
    ]
