# Generated by Django 4.0.4 on 2023-01-27 08:48

from django.db import migrations, models
from django.db.models import Q
import django.db.models.deletion
import django.utils.timezone



def forwards_func(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    MediaFolder = apps.get_model("camomilla", "MediaFolder")
    for folder in MediaFolder.objects.using(db_alias).filter(Q(name__isnull=True) | Q(name="")):
        folder.name = folder.title_en or folder.title_it or "folder_%s" % folder.pk
        folder.save(update_fields=["name"])
    Tag = apps.get_model("camomilla", "Tag")
    for tag in Tag.objects.using(db_alias).filter(Q(name__isnull=True) | Q(name="")):
            tag.name = "tag_%s" % tag.pk
            tag.save(update_fields=["name"])       
            

class Migration(migrations.Migration):

    dependencies = [
        ('camomilla', '0012_modeltranslation'),
    ]

    operations = [
        migrations.CreateModel(
            name='UrlNode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permalink', models.CharField(max_length=400, unique=True)),
                ('permalink_it', models.CharField(max_length=400, null=True, unique=True)),
                ('permalink_en', models.CharField(max_length=400, null=True, unique=True)),
                ('related_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ('ordering',), 'verbose_name': 'Page', 'verbose_name_plural': 'Pages'},
        ),
        migrations.RenameField(
            model_name='article',
            old_name='date',
            new_name='date_updated_at',
        ),
        migrations.RenameField(
            model_name='mediafolder',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='media',
            old_name='alt_text',
            new_name='alt_tag',
        ),
        migrations.RenameField(
            model_name='media',
            old_name='alt_text_en',
            new_name='alt_tag_en',
        ),
        migrations.RenameField(
            model_name='media',
            old_name='alt_text_it',
            new_name='alt_tag_it',
        ),
        migrations.RenameField(
            model_name='media',
            old_name='description',
            new_name='description_tag',
        ),
        migrations.RenameField(
            model_name='media',
            old_name='description_en',
            new_name='description_tag_en',
        ),
        migrations.RenameField(
            model_name='media',
            old_name='description_it',
            new_name='description_tag_it',
        ),
        migrations.RenameField(
            model_name='media',
            old_name='name',
            new_name='title_tag',
        ),
        migrations.RenameField(
            model_name='media',
            old_name='title',
            new_name='title_tag_en',
        ),
        migrations.RenameField(
            model_name='media',
            old_name='title_en',
            new_name='title_tag_it',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='title_it',
            new_name='name_it',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='title_en',
            new_name='name_en',
        ),
        migrations.RemoveField(
            model_name='article',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='article',
            name='identifier',
        ),
        migrations.RemoveField(
            model_name='article',
            name='permalink',
        ),
        migrations.RemoveField(
            model_name='article',
            name='permalink_en',
        ),
        migrations.RemoveField(
            model_name='article',
            name='permalink_it',
        ),
        migrations.RemoveField(
            model_name='content',
            name='permalink',
        ),
        migrations.RemoveField(
            model_name='content',
            name='permalink_en',
        ),
        migrations.RemoveField(
            model_name='content',
            name='permalink_it',
        ),
        migrations.RemoveField(
            model_name='content',
            name='subtitle',
        ),
        migrations.RemoveField(
            model_name='content',
            name='subtitle_en',
        ),
        migrations.RemoveField(
            model_name='content',
            name='subtitle_it',
        ),
        migrations.RemoveField(
            model_name='content',
            name='title',
        ),
        migrations.RemoveField(
            model_name='content',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='content',
            name='title_it',
        ),
        migrations.RemoveField(
            model_name='media',
            name='title_it',
        ),
        migrations.RemoveField(
            model_name='mediafolder',
            name='description',
        ),
        migrations.RemoveField(
            model_name='mediafolder',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='mediafolder',
            name='description_it',
        ),
        migrations.RemoveField(
            model_name='mediafolder',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='page',
            name='identifier',
        ),
        migrations.RemoveField(
            model_name='page',
            name='permalink',
        ),
        migrations.RemoveField(
            model_name='page',
            name='permalink_en',
        ),
        migrations.RemoveField(
            model_name='page',
            name='permalink_it',
        ),
        migrations.AddField(
            model_name='article',
            name='breadcrumbs_title',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='indexable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='article',
            name='parent_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_child_pages', to='camomilla.article'),
        ),
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='page',
            name='breadcrumbs_title',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='breadcrumbs_title_en',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='breadcrumbs_title_it',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='page',
            name='date_updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='page',
            name='indexable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='page',
            name='indexable_en',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='page',
            name='indexable_it',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='page',
            name='parent_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_child_pages', to='camomilla.page'),
        ),
        migrations.AddField(
            model_name='page',
            name='pubblication_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='page',
            name='slug_en',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='slug_it',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='status',
            field=models.CharField(choices=[('PUB', 'Published'), ('DRF', 'Draft'), ('TRS', 'Trash'), ('PLA', 'Planned')], default='DRF', max_length=3),
        ),
        migrations.AddField(
            model_name='page',
            name='status_en',
            field=models.CharField(choices=[('PUB', 'Published'), ('DRF', 'Draft'), ('TRS', 'Trash'), ('PLA', 'Planned')], default='DRF', max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='status_it',
            field=models.CharField(choices=[('PUB', 'Published'), ('DRF', 'Draft'), ('TRS', 'Trash'), ('PLA', 'Planned')], default='DRF', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='canonical',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='canonical_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='canonical_it',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='description_it',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='highlight_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_highlight_images', to='camomilla.media'),
        ),
        migrations.AlterField(
            model_name='article',
            name='meta',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='article',
            name='og_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='og_description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='og_description_it',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='og_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_og_images', to='camomilla.media'),
        ),
        migrations.AlterField(
            model_name='article',
            name='og_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='og_title_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='og_title_it',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='og_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='og_type_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='og_type_it',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='og_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='og_url_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='og_url_it',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(to='camomilla.tag'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='title_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='title_it',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='identifier',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='mediafolder',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='canonical',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='canonical_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='canonical_it',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='description_it',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='meta',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='page',
            name='og_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='og_description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='og_description_it',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='og_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_og_images', to='camomilla.media'),
        ),
        migrations.AlterField(
            model_name='page',
            name='og_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='og_title_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='og_title_it',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='og_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='og_type_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='og_type_it',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='og_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='og_url_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='og_url_it',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='title_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='title_it',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.AddField(
            model_name='article',
            name='url_node',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='camomilla.urlnode'),
        ),
        migrations.AddField(
            model_name='page',
            name='url_node',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='camomilla.urlnode'),
        ),
        migrations.RunPython(forwards_func, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='mediafolder',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='mediafolder',
            name='title_it',
        ),
        migrations.AlterField(
            model_name='mediafolder',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
