# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-10 17:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camomilla', '0013_auto_20170627_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='date_to_show',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
