# Generated by Django 4.0.4 on 2023-02-02 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camomilla', '0013_urlnode_alter_page_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=200, unique=True)),
                ('available_classes', models.JSONField(default=dict)),
                ('enabled', models.BooleanField(default=True)),
                ('nodes', models.JSONField(default=list)),
                ('nodes_it', models.JSONField(default=list, null=True)),
                ('nodes_en', models.JSONField(default=list, null=True)),
            ],
            options={
                'verbose_name': 'menu',
                'verbose_name_plural': 'menus',
            },
        ),
    ]
