# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-23 22:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camomilla', '0014_article_date_to_show'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitemapurl',
            options={'permissions': (('read_sitemapurl', 'Can read sitemap url'),), 'verbose_name': 'Page', 'verbose_name_plural': 'Pages'},
        ),
        migrations.RenameField(
            model_name='article',
            old_name='date_to_show',
            new_name='pubblication_date',
        ),
        migrations.RenameField(
            model_name='sitemapurl',
            old_name='page',
            new_name='identifier',
        ),
        migrations.RemoveField(
            model_name='content',
            name='author',
        ),
        migrations.RemoveField(
            model_name='content',
            name='date',
        ),
        migrations.RemoveField(
            model_name='content',
            name='status',
        ),
        migrations.AlterField(
            model_name='articletranslation',
            name='permalink',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
