# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-23 23:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('camomilla', '0015_auto_20171123_2300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articletranslation',
            name='slug',
        ),
    ]
