# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-27 11:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camomilla', '0016_remove_articletranslation_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articletranslation',
            name='og_description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='sitemapurltranslation',
            name='og_description',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
