# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-10-02 12:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('camomilla', '0021_auto_20180927_1316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='og_image',
        ),
        migrations.RemoveField(
            model_name='sitemapurl',
            name='og_image',
        ),
        migrations.AddField(
            model_name='article',
            name='og_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='camomilla_article_related', to='camomilla.Media'),
        ),
        migrations.AddField(
            model_name='sitemapurl',
            name='og_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='camomilla_sitemapurl_related', to='camomilla.Media'),
        ),
        migrations.AddField(
            model_name='article',
            name='trash',
            field=models.BooleanField(default=False),
        ),
    ]
