# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-10-04 12:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camomilla', '0023_articletranslation_content_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('PUB', 'Published'), ('DRF', 'Draft'), ('TRS', 'Trash'), ('PLA', 'Planned')], default='DRF', max_length=3),
        ),
    ]
