# Generated by Django 2.2 on 2020-04-22 15:05

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('camomilla', '0026_auto_20181114_2248'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SitemapUrl',
            new_name='Page',
        ),
        migrations.RenameModel(
            old_name='SitemapUrlTranslation',
            new_name='PageTranslation',
        ),
    ]
