# Generated by Django 2.2 on 2020-04-22 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('camomilla', '0027_auto_20200422_1505'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='content',
            options={},
        ),
        migrations.AlterModelOptions(
            name='media',
            options={'ordering': ['-pk']},
        ),
        migrations.AlterModelOptions(
            name='page',
            options={'verbose_name': 'Page', 'verbose_name_plural': 'Pages'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={},
        ),
        migrations.RemoveField(
            model_name='articletranslation',
            name='content_title',
        ),
        migrations.AlterField(
            model_name='articletranslation',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='articletranslation',
            name='permalink',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='content',
            name='page',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contents', to='camomilla.Page'),
        ),
        migrations.AlterField(
            model_name='contenttranslation',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='contenttranslation',
            name='permalink',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='og_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='camomilla_page_related', to='camomilla.Media'),
        ),
        migrations.AlterModelTable(
            name='pagetranslation',
            table='camomilla_page_translation',
        ),
    ]
