# Generated by Django 2.2.17 on 2021-05-11 09:39

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('camomilla', '0028_auto_20200422_1615'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='article',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_plain_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='article',
            name='trash',
        ),
        migrations.AddField(
            model_name='mediafolder',
            name='path',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mediafolder',
            name='updir',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_folders', to='camomilla.MediaFolder'),
        ),
    ]
